### ISSUE TITLE
Use tags instead of bundle configuration for event providers

### ISSUE THREAD

**Issue by yohang** [frequence-web/FrequenceWebCalendRBundle#1]
use

``` yaml
services:
    my_event_provider:
        class: My\Event\Provider
        tags:
            - { name: calendr.event_provider }
```

instead of

``` yaml
frequence_web_calend_r:
    event_providers:
        - my_event_provider
```
